export const SEC = {
  statement: ["Statement"],
  account: ["Account information", "Account Information", "Kontoinformation"],
  nav: ["Net asset value", "Net Asset Value", "Nettovermögenswert"],
  changeInNav: ["Change in NAV", "Change in Nav", "Veränderung des Nettovermögenswerts"],
  positions: ["Open positions", "Open Positions", "Offene Positionen"],
  forex: ["Foreign exchange positions", "Forex Balances", "Devisenpositionen"],
  transactions: ["transactions", "Transactions", "Trades", "Transaktionen"],
  dividends: ["Dividends", "Dividenden"],
  withholdingTax: ["Withholding tax", "Withholding Tax", "Quellensteuer"],
  depositsWithdrawals: [
    "Deposits and withdrawals",
    "Deposits & Withdrawals",
    "Ein- und Auszahlungen",
  ],
  fees: ["Fees", "Gebühren"],
  interest: [
    "Margin interest rates",
    "Margin Interest",
    "Interest",
    "Zinsen",
    "Margin-Zinssätze",
  ],
  marginOverview: ["Margin overview", "Margin Overview", "Margin-Übersicht"],
  performance: [
    "Overview of realized and unrealized performance",
    "Realized & Unrealized Performance Summary",
    "Übersicht realisierte und unrealisierte Performance",
  ],
  forexPnl: [
    "Forex profit and loss details",
    "Forex P/L Details",
    "Devisengewinne und -verluste",
  ],
} as const;
